name: Deploy mdBook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - run: mdbook build STM32F4-RS-BOOK

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./STM32F4-RS-BOOK/book
